"""auto update

Revision ID: 5e5a2b8d8f4f
Revises: 2ca2ee9c28cc
Create Date: 2026-03-20 06:36:05.557784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5a2b8d8f4f'
down_revision: Union[str, Sequence[str], None] = '2ca2ee9c28cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('meal_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('meal_logs', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meal_logs', 'food_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('meal_plans', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_profiles', 'height_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('weight_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('weight_logs', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_logs', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('weight_logs', 'created_at')
    op.alter_column('user_profiles', 'height_cm',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('user_profiles', 'created_at')
    op.alter_column('recipes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('recipes', 'created_at')
    op.drop_column('meal_plans', 'created_at')
    op.alter_column('meal_logs', 'food_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meal_logs', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('meal_logs', 'created_at')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###